version: '3.8'

services:
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: backend-service
    environment:
      DB_HOST: your-rds-endpoint.amazonaws.com
      DB_PORT: 3306
      DB_NAME: studentapp
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: frontend-service
    ports:
      - "80:80"
    depends_on:
      - backend